# Generated by Django 5.1.6 on 2025-02-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('challenge_type', models.CharField(choices=[('predefined', 'Predefined'), ('custom', 'Custom')], max_length=20)),
                ('start_word', models.CharField(max_length=100)),
                ('end_word', models.CharField(max_length=100)),
                ('ai_hint', models.CharField(choices=[('A*', 'A*'), ('UCS', 'UCS'), ('BFS', 'BFS')], max_length=20)),
                ('input_word', models.CharField(max_length=100)),
            ],
        ),
    ]
