# Generated by Django 5.1.6 on 2025-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='ladder',
            field=models.JSONField(default=list),
        ),
    ]
